### ISSUE TITLE
ArrayIndexOutOfBoundsException when running on Jace.jar

### ISSUE THREAD

**Issue by gungwald** [nemecec/retrotranslator#1]
> [bill@localhost lib]$ retrotranslator.sh Jace.jar jace-backport.jar
> Processing 2769 file(s) from Jace.jar to jace-backport.jar.
> com/google/common/reflect/TypeToken$TypeCollector.class
>     Repetitive method removed: collectTypes
> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 49097
> 	at net.sf.retrotranslator.runtime.asm.ClassReader.<init>(ClassReader.java:112)
> 	at net.sf.retrotranslator.transformer.ClassTransformer.transform(ClassTransformer.java:105)
> 	at net.sf.retrotranslator.transformer.FileTranslator.transform(FileTranslator.java:90)
> 	at net.sf.retrotranslator.transformer.FileTranslator.transform(FileTranslator.java:69)
> 	at net.sf.retrotranslator.transformer.Retrotranslator.run(Retrotranslator.java:212)
> 	at net.sf.retrotranslator.transformer.Retrotranslator.execute(Retrotranslator.java:353)
> 	at net.sf.retrotranslator.transformer.Retrotranslator.main(Retrotranslator.java:372)

**Comment by nemecec** [comment]
Sorry for late reaction.
Can you provide a bundle that I can use to reproduce this issue on my machine? I remember seeing a similar error at some point but I do not remember the cause.
You are trying to retrotranslate https://github.com/cowwoc/jace/?

**Comment by nemecec** [comment]
Closing the issue due to inactivity and lack of information necessary for troubleshooting.

Reopen in case you can share more information about this.
